version: '3'

services:
  app:
    build: .
    ports:
      - "7099:7099"
    depends_on:
      - db
    environment:
      - DB_URL=jdbc:postgresql://localhost:5432/fileManagement
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres

  db:
    build: ./db
    ports:
      - "5432:5432"